fix: agent id obs spec dtype
instadeepai/Mava pull request #1016
Opened 2024-02-12 15:04 UTC by sash-a

## What?
Agent ID wrapper assumed that the obs dtype was int (discrete) this is no longer the case as we support continuous envs.

1 liner to fix this

2024-02-13 11:06 UTC, RuanJohn approved these changes, later dismissed
Good catch! Thanks @sash-a :fire:

2024-02-13 11:36 UTC, OmaymaMahjoub approved these changes
nice catch :eyes:

2024-02-13 11:37 UTC, OmaymaMahjoub requested changes
Can you do the same for global_state = specs.Array(state_shape, jnp.int32, "global_state") (line 95)

2024-02-14 07:52 UTC, sash-a commented
> Can you do the same for `global_state = specs.Array(state_shape, jnp.int32, "global_state")` (line 95)

Great catch @OmaymaMahjoub, fixed that one and another one in the `GlobalStateWrapper`

2024-02-14 08:51 UTC, OmaymaMahjoub submitted a review, later dismissed
:fire:

2024-02-14 08:54 UTC, RuanJohn commented on mava/wrappers/observation.py
> +            global_state = specs.Array(state_shape, dtype, "global_state")
Quite a nit question, but can't there be weird cases where a global state has a different dtype than the agent's view?

2024-02-14 09:05 UTC, RuanJohn approved these changes
LGTM. Thanks @sash-a!

2024-02-14 09:07 UTC, OmaymaMahjoub approved these changes
:fire:

2024-02-14 09:10 UTC, merged