fix: initialize max_episode_return to negative infinity instead of zero for each algorithm
instadeepai/Mava pull request #1024
Opened 2024-02-15 14:09 UTC by SimonDuToit

2024-02-15 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instadeepai/Mava?pullRequest=1024) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instadeepai/Mava?pullRequest=1024) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instadeepai/Mava?pullRequest=1024) it.</sub>

2024-02-15 14:34 UTC, sash-a requested changes
Just a minor style change, thanks for finding this bug! Can you also do this for the ppo file in the advanced usage folder :smile:

2024-02-15 14:34 UTC, sash-a commented on mava/systems/ff_ippo.py
> +    max_episode_return = jnp.float32(-jnp.inf)
We don't actually need the `jnp.float32` part :smile: 

```suggestion
    max_episode_return = -jnp.inf
```

2024-02-15 14:34 UTC, sash-a commented on mava/systems/ff_mappo.py
> +    max_episode_return = jnp.float32(-jnp.inf)
```suggestion
    max_episode_return = -jnp.inf
```

2024-02-15 14:34 UTC, sash-a commented on mava/systems/rec_ippo.py
> +    max_episode_return = jnp.float32(-jnp.inf)
```suggestion
    max_episode_return = -jnp.inf
```

2024-02-15 14:34 UTC, sash-a commented on mava/systems/rec_mappo.py
> +    max_episode_return = jnp.float32(-jnp.inf)
```suggestion
    max_episode_return = -jnp.inf
```

2024-02-15 14:34 UTC, RuanJohn approved these changes, later dismissed
Good catch! And great first PR :fire:

2024-02-15 14:51 UTC, SimonDuToit commented
I've removed the float conversions and added it to the advanced usage file.

2024-02-15 14:52 UTC, sash-a approved these changes
:fire: :rocket: :1st_place_medal:

2024-02-16 10:00 UTC, RuanJohn approved these changes
Thanks @SimonDuToit :raised_hands:

2024-02-16 13:21 UTC, merged