feat: cnn support for recurrent systems
instadeepai/Mava pull request #1067
Opened 2024-03-19 15:05 UTC by SimonDuToit

Previously it was not possible to use a CNN in Mava's recurrent systems. This PR makes CNNs compatible with recurrent systems and adds a relevant config for a recurrent CNN network.

2024-03-19 15:13 UTC, sash-a requested changes
Small change otherwise looks good. Can we just wait till we've run a couple experiments on connector to see that the recurrent systems perform ok :pray:

2024-03-19 15:13 UTC, sash-a commented on mava/networks.py
> +        return jax.lax.collapse(x, -3)
I'd say remove the comment above for these two
```suggestion
        # Collapse (merge) the last three dimensions (width, height, channels)
        # Leave the batch, agent and time (if recurrent) dims unchanged.
        return jax.lax.collapse(x, -3)
```

2024-05-13 10:06 UTC, sash-a approved these changes
Thanks @SimonDuToit :fire:

2024-07-05 09:42 UTC, OmaymaMahjoub approved these changes
Thanks @SimonDuToit :fire:

2024-07-05 10:44 UTC, merged