Chore: anakin and sebulba folders
instadeepai/Mava pull request #1090
Opened 2024-07-16 11:31 UTC by Louay-Ben-nessir

## What?
Changed the systems folder structure. 
## Why?
To create a folder for Sebulba systems. 
## How?
copied all of the Anakin systems into their own folder.

2024-07-17 08:50 UTC, sash-a requested changes
Please make the changes to the sac and q learning files for the hydra config and types. Double check that it runs :pray:

2024-07-17 08:50 UTC, sash-a commented on mava/systems/anakin/sac/ff_isac.py
The same thing needs to be done to the hydra config path in the q learning and SAC files and also the import of their types

2024-07-17 08:50 UTC, sash-a commented on mava/utils/checkpointing.py
> +from mava.systems.anakin.ppo.types import HiddenStates, Params
We definitely shouldn't be using a PPO type here, but I guess that is not the concern of this PR.

2024-07-17 14:49 UTC, sash-a commented
Just wondering if it makes sense to have the anakin/sebulba split one folder deeper so instead of `anakin/ppo` it'll be `ppo/anakin`. The reason I say this is to have a shared types files, because I assume a lot of the types we already will be useful to sebulba. @Louay-Ben-nessir have you used the types we already have like `HiddenStates`/`LearnerState` etc?

2024-07-17 15:07 UTC, RuanJohn approved these changes
Thank you @Louay-Ben-nessir!

2024-07-19 14:34 UTC, sash-a approved these changes
Thanks @Louay-Ben-nessir :fire:

2024-07-23 07:48 UTC, merged