Feat: sebulba rec ippo
instadeepai/Mava pull request #1142
Opened 2024-11-18 16:14 UTC by SimonDuToit

Sebulba implementation of recurrent IPPO. Also fixes a problem in the sebulba systems where single_action_space actually refered to the combined action space across agents.

2024-12-11 13:40 UTC, OmaymaMahjoub requested changes
Overall the system looks correct and reasonable. Well done Simon! I just kept minor requests :)

2024-12-11 13:40 UTC, OmaymaMahjoub commented on mava/configs/default/rec_ippo_sebulba.yaml
> +  - env: lbf_gym  # [rware_gym, lbf_gym]
if you can add smaclite_gym to the list

2024-12-11 13:40 UTC, OmaymaMahjoub commented on mava/systems/ppo/sebulba/rec_ippo.py
> +        key: chex.PRNGKey,
```suggestion
        dones: chex.Array,
        hstates: HiddenStates,
```

2024-12-11 13:40 UTC, OmaymaMahjoub commented on mava/systems/ppo/sebulba/rec_ippo.py
> +# Copyright 2022 InstaDeep Ltd. All rights reserved.
If you can update the typings in Pipeline `mava/utils/sebulba.py` to be `Union[PPOTransition, RNNPPOTransition]`

2024-12-11 13:40 UTC, OmaymaMahjoub commented on mava/systems/ppo/sebulba/rec_ippo.py
> +        # value = critic_apply_fn(params.critic_params, observation).squeeze()
if you can remove this comment

2024-12-11 13:40 UTC, OmaymaMahjoub commented on mava/systems/ppo/sebulba/rec_ippo.py
> +    # simon
same here once you are done from cleaning, if you can remove this comment

2024-12-11 13:40 UTC, OmaymaMahjoub commented on mava/systems/ppo/sebulba/rec_ippo.py
> +    # simon
I see this comment exists in multiple lines, if you can remove them all

2024-12-11 13:40 UTC, OmaymaMahjoub commented on mava/systems/ppo/sebulba/rec_ippo.py
> +        # learner_state = LearnerState(params, opt_states, key, None, learner_state.timestep)
If you can remove this comment

2025-01-07 14:28 UTC, SimonDuToit commented on mava/systems/ppo/sebulba/rec_ippo.py
> +# Copyright 2022 InstaDeep Ltd. All rights reserved.
This causes errors in the pre-commit. For now I changed both sebulba systems to use the `MavaTransition` type-var but this is probably a temporary solution.

2025-01-09 09:32 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +# Copyright 2022 InstaDeep Ltd. All rights reserved.
Can you please make an issue for this. I think the best solution is to make a protocol with the all the common things in a transition (actions, obs, done, reward). The challenge is that named tuples don't seem to work with protocols so we'd likely need to switch to a flax/chex dataclass

2025-01-09 11:38 UTC, sash-a requested changes
Looks great! Pretty much good to go except a few minor style changes to bring it up to date with the latest PPO changes that went in at the end of last year

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                # UNPACK TRAIN STATE AND BATCH INFO
In line with PPO updates I did last year

```suggestion
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                    # RERUN NETWORK
```suggestion
                    # Rerun network
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                    # RERUN NETWORK
```suggestion
                    # Rerun network
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                    # CALCULATE VALUE LOSS
```suggestion
                    # Calculate value loss
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                    return total_loss, (loss_actor, entropy)
```suggestion
                    actor_loss1 = ratio * gae
                    actor_loss2 = (
                        jnp.clip(
                            ratio,
                            1.0 - config.system.clip_eps,
                            1.0 + config.system.clip_eps,
                        )
                        * gae
                    )
                    actor_loss = -jnp.minimum(actor_loss1, actor_loss2)
                    actor_loss = actor_loss.mean()
                    # The seed will be used in the TanhTransformedDistribution:
                    entropy = actor_policy.entropy(seed=key).mean()

                    total_loss = actor_loss - config.system.ent_coef * entropy
                    return total_loss, (actor_loss, entropy)
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +    # # Load model from checkpoint if specified.
```suggestion
    # Load model from checkpoint if specified.
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                    return total_loss, value_loss
```suggestion
                    total_value_loss = config.system.vf_coef * value_loss
                    return total_value_loss, value_loss
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                critic_loss_info, critic_grads = critic_grad_fn(
```suggestion
                value_loss_info, critic_grads = critic_grad_fn(
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                )
```suggestion
                critic_grads, value_loss_info = jax.lax.pmean(
                    (critic_grads, value_loss_info), axis_name="learner_devices"
                )
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                }
```suggestion
                actor_loss, (_, entropy) = actor_loss_info
                value_loss, (unscaled_value_loss) = value_loss_info
                total_loss = actor_loss + value_loss
                loss_info = {
                    "total_loss": total_loss,
                    "value_loss": unscaled_value_loss,
                    "actor_loss": actor_loss,
                    "entropy": entropy,
                }
```

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                    num_learner_envs * num_recurrent_chunks,
Can you extract this into a variable called `batch_size`. Will make it more clear and it's also used below

2025-01-09 11:38 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +            # permutation = jax.random.permutation(shuffle_key, batch_size)
```suggestion
```

2025-01-15 08:57 UTC, sash-a reviewed
Final minor comments

2025-01-15 08:57 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +    hstates_tpu = tree.map(move_to_device, hstates)
`device_put` already tree maps
```suggestion
    hstates_tpu = move_to_device(hstates)
```

2025-01-15 08:57 UTC, sash-a commented on mava/systems/ppo/sebulba/rec_ippo.py
> +                last_dones = tree.map(move_to_device, dones)
```suggestion
                obs_tpu = move_to_device(timestep.observation)
                last_dones = move_to_device(dones)
```

2025-01-28 15:52 UTC, closed without merging