Feat Sebulba recurrent IQL
instadeepai/Mava pull request #1148
Opened 2024-12-04 14:01 UTC by Louay-Ben-nessir

## What?
A recurrent IQL implementation using the Sebulba architecture.
## Why?
Offline Sebulba base and non-jax envs in Mava.
## How?
Mixed the Sebulba structure from PPO with the learner code from Anakin IQL.

2025-01-07 11:38 UTC, sash-a requested changes
I've looked through everything except the system file and it looks good, Sebulba utils especially! Just some relatively minor style changes

2025-01-07 11:38 UTC, sash-a commented on mava/configs/system/q_learning/rec_iql.yaml
> +rollout_length:  2 # Number of environment steps per vectorised enviro²nment.
Not sure how the ^2 got in there :joy: 
```suggestion
rollout_length: 2 # Number of environment steps per vectorised environment.
```

2025-01-07 11:38 UTC, sash-a commented on mava/systems/q_learning/types.py
> +from mava.types import MavaObservation, Observation
Where do we still use `Observation`? Can we use `MavaObservation` everywhere?

2025-01-07 11:38 UTC, sash-a commented on mava/utils/config.py
> +        )
A thought on this, maybe we can split these up into multiple methods e.g `check_num_updates`, `check_num_envs` etc. Then have a `check_sebulba_config_ppo`, `check_anakin_config_ppo` and a `check_sebulba_config_iql` which will use the relevant methods?

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> -# todo: remove the ppo dependencies when we make sebulba for other systems
This is a good point though, maybe there's something we can do about it :thinking:

Maybe a protocol like that has `action, obs, reward`, not sure if there's any other common attributes?

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +class RateLimiter:
This file is getting quite long, can we structure it like this:
```
-utils/
--sebulba/
---utils.py
---rate_limiters.py
---pipelines.py
```

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        lifetime: ThreadLifetime,
While we're here, I think we should actually replace the lifetime with `threading.Event`, [it's a python builtin](https://docs.python.org/3/library/threading.html#event-objects) that does exactly what we want. Although maybe that should be a separate, I'll make an issue

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        self.move_to_device = lambda tree: jax.tree.map(lambda x: jax.device_put(x, self.cpu), tree)
Seems like this is unused, would just be `device_get` anyway

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        traj = jax.device_get(traj)
Maybe be better to do the device get first so we block the device as little as possible? Although it's probably a tiny difference

```suggestion
        traj = jax.device_get(traj)
        traj = _stack_trajectory(traj)
```

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        ]
Not sure I follow why this could deadlock?

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        transitions: Transition = jax.tree_map(lambda *x: np.concatenate(x), *sampled_batch)
nit
```suggestion
        transitions: Transition = tree.map(lambda *x: np.concatenate(x), *sampled_batch)
```

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        if not self._queue.empty():
Can we rename this to `metrics_queue`, wasn't clear what this was storing

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        self.deletes = 0
Wonder if we need deletes here?

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +    ):
Can we please add a good doc string here please :pray:

2025-01-07 11:38 UTC, sash-a commented on mava/utils/sebulba.py
> +        if isinstance(error_buffer, float) or isinstance(error_buffer, int):
nit

```suggestion
        if isinstance(error_buffer, (int, float)):
```

2025-01-07 11:38 UTC, sash-a commented on mava/wrappers/gym.py
> +        )  # (B,) --> (B, N)
Does this already happen for smax and lbf?

2025-01-08 14:00 UTC, sash-a requested changes
Great work here! Really minor changes required. Happy to merge this pending some benchmarks

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +        action = action[0, ...]  # (1, B, A) -> (B, A)
Bit safer as this will silently error if actions 0 dim is ever larger than 1

```suggestion
        action = eps_greedy_dist.sample(seed=key).squeeze(0)  # (B, A)
```

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +                terminal = (1 - timestep.discount[..., 0, jnp.newaxis]).astype(bool)
Are you sure we want to remove the agent dim here?

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +                hidden_state, obs_term_or_trunc = prep_inputs_to_scannedrnn(obs, term_or_trunc)
A general comment, I think this would be a lot easier to read if we used `done` to mean `term_or_trunc` which I think is a reasonable thing. Would have to make the change in anakin also though :/

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +        timing_dict = tree.map(np.mean, timing_dict, is_leaf=lambda x: isinstance(x, list))
2 things, can we call this time_metrics and can you add a shape explainer comment as it's a bit hard to work out what is happening here

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +            config.system.eps_min, 1 - (t / config.system.eps_decay) * (1 - config.system.eps_min)
Would be nice if we could set a different decay per actor, although I think that's out of scope for this PR. Maybe if you could make an issue to add in some of the ape-X DQN features that would be great

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +                last_dones = tree.map(move_to_device, dones)
`device_put` will automatically `tree_map`
```suggestion
                obs_tpu = move_to_device(timestep.observation)
                last_dones = move_to_device(dones)
```

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +    # create temporory envoirnments.
nit
```suggestion
    # create temporary environments.
```

2025-01-08 14:00 UTC, sash-a commented on mava/configs/system/q_learning/rec_iql.yaml
> +data_sample_mean: 150  # Average number of times the learner should sample each item from the replay buffer.
Can we rather call this: `mean_data_sample_rate`. Wasn't clear to me what it was when I read it in the system file

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +    rate_limiter = SampleToInsertRatio(config.sample_per_insert, min_num_inserts, config.tolerance)
We should probably put them in the system config so it's easier to find on things like neptune

```suggestion
    config.system.sample_per_insert = config.system.data_sample_mean * insert_to_sample_ratio
    config.system.tolerance = config.sample_per_insert * config.system.error_tolerance

    min_num_inserts = max(
        config.system.sample_sequence_length // config.system.rollout_length,
        config.system.min_buffer_size // config.system.rollout_length,
        1,
    )

    rate_limiter = SampleToInsertRatio(config.system.sample_per_insert, min_num_inserts, config.system.tolerance)
```

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +            logger.log(train_metrics, t, eval_step, LogEvent.TRAIN)
I think we should always log train metrics even if an episode hasn't finished yet, what do you think?

2025-01-08 14:00 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +        if config.arch.absolute_metric and max_episode_return <= episode_return:
I never know what order the bools will be evaluated in so I always add brackets, because it might be doing `(config.arch.absolute_metric and max_episode_return) <= episode_return`
```suggestion
        if config.arch.absolute_metric and (max_episode_return <= episode_return):
```

2025-01-15 09:58 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +                dones = next_timestep.last()[..., jnp.newaxis]
Can we call this `next_done` just so it's clear which step it's aligned with

2025-01-22 16:51 UTC, Louay-Ben-nessir commented on mava/utils/config.py
> +        )
I split it into base_sebulba_checks and ppo_sebulba_checks. Any more splits feel excessive 🤔

2025-01-22 16:52 UTC, Louay-Ben-nessir commented on mava/utils/sebulba.py
> +        self.deletes = 0
nope, just removed it and the related functions!

2025-01-22 16:56 UTC, Louay-Ben-nessir commented on mava/systems/q_learning/sebulba/rec_iql.py
> +                terminal = (1 - timestep.discount[..., 0, jnp.newaxis]).astype(bool)
The dones flag is removed here and added back in the scannedRNN. We could either modify the RNN to handle the dones flag with or without the agent dimension or standardize it by keeping the agent dimension across all scripts. 🤔

2025-02-06 13:29 UTC, SimonDuToit reviewed
Great work Louay! Just two questions from my side as you can see in the comments.

2025-02-06 13:29 UTC, SimonDuToit commented on mava/wrappers/gym.py
> +        terminated = np.zeros((num_envs, self.num_agents), dtype=float)
I assume with this change we would also need to change sebulba PPO? Since currently it does this same operation. We should decide if generally its better doing this in the system or the wrapper.

2025-02-06 13:29 UTC, SimonDuToit commented on mava/utils/sebulba/pipelines.py
> +        self._stop_event.set()
Just to check: the Pipeline class is unchanged from the original one in utils/sebulba, right?

2025-02-10 08:48 UTC, sash-a requested changes
Looks great to me, just a few minor things :pray:

2025-02-10 08:48 UTC, sash-a commented on mava/utils/sebulba/pipelines.py
> +        self._stop_event.set()
This is a nice change, although I don't think it needs to be an event in this case, it can just be a bool. Because it's internal to this thread and there's no chance of a deadlock here since once you call stop nothing else will start the thread again :+1:

2025-02-10 08:48 UTC, sash-a commented on mava/utils/sebulba/pipelines.py
> +        # [{'metric1' : value1, ...} * rollout_len -> {'metric1' : [value1, value2, ...], ...}
While we're here, this comment has been wrong for a while :joy: 
```suggestion
        # [{'metric1' : value1}, ...] * rollout_len -> {'metric1' : [value1, value2, ...], ...}
```

2025-02-10 08:48 UTC, sash-a commented on mava/utils/sebulba/pipelines.py
> +        self._stop_event = threading.Event()
Similar here, this can just be a bool

2025-02-10 08:48 UTC, sash-a commented on mava/utils/sebulba/pipelines.py
> +        self.metrics_queue: queue.Queue = queue.Queue(maxsize=100)
```suggestion
        # Only keep the latest 100 metrics, otherwise too many metrics are added we risk an OOM
        self.metrics_queue: queue.Queue = queue.Queue(maxsize=100)
```

2025-02-10 08:48 UTC, sash-a commented on mava/utils/sebulba/pipelines.py
> +        self.buffer_adds_count[actor_id] += 1
Do we still need this, seem it isn't used?

I think there's also a property of the buffer state we can use if we want to get the size

2025-02-10 08:48 UTC, sash-a commented on mava/configs/system/q_learning/rec_iql.yaml
> +error_tolerance:  ~ # Tolerance for how much the learner/actor can sample/insert before being blocked. Must be greater than 2 to avoid deadlocks.
I think this is a slightly better explainer

```suggestion
error_tolerance: float  # Maximum allowed deviation from the target sampling ratio. Controls how far the actual samples can vary from the ideal samples-per-insert ratio. Must be > 2 to prevent deadlocks.
```

Also let's give this a value, because I think the blocking one might be too blocking so would be nice to make this the default. A value of ~4 seems good to me what did you find in your experiments?

2025-02-10 08:48 UTC, sash-a commented on mava/utils/sebulba/rate_limiters.py
This is really great!

2025-02-10 08:48 UTC, sash-a commented on mava/utils/sebulba/utils.py
> +        self._stop_event = threading.Event()
Same here for being a bool

2025-02-10 08:48 UTC, sash-a commented on mava/wrappers/gym.py
> +        terminated = np.zeros((num_envs, self.num_agents), dtype=float)
Good point, I think we do this in the wrappers for the anakin systems

2025-02-10 08:48 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +        thread_lifetime: Controls the thread's lifecycle.
```suggestion
        stop_event: used to inform this thread that it is time to stop.
```

2025-02-10 08:48 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +    rollout_queue: Pipeline,
In this case it's not a queue, because we're using a replay buffer. Can we rename this to pipeline

2025-02-10 08:48 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +            # [{metric1 : (num_envs, ...), ...} * n_rollouts] -->
```suggestion
            # [{metric1 : (num_envs, ...)}, ...] * n_rollouts -->
```

2025-02-10 08:48 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +            # [{metric1: value1, ...} * n_rollouts] -->
```suggestion
            # [{metric1: value1}, ...] * n_rollouts -->
```

2025-02-10 08:48 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +    print(f"{Fore.RED}{Style.BRIGHT}All threads stopped...{Style.RESET_ALL}")
Can we make this a function in sebulba/utils? And then use it in PPO also because it should be the same right?

2025-02-10 12:25 UTC, Louay-Ben-nessir commented on mava/utils/sebulba/pipelines.py
> +        self._stop_event.set()
small change, removed the Threadlifetime. Everything else in the same

2025-02-10 13:05 UTC, Louay-Ben-nessir commented on mava/utils/sebulba.py
> +        ]
I don't remember exactly 😅 
it has something to do with the states inside the buffer array possibly changing while we loop over them 🤔

2025-02-10 13:07 UTC, Louay-Ben-nessir commented on mava/systems/q_learning/sebulba/rec_iql.py
> +            config.system.eps_min, 1 - (t / config.system.eps_decay) * (1 - config.system.eps_min)
I can easily add this in this PR 👀

2025-02-10 13:18 UTC, Louay-Ben-nessir commented on mava/utils/sebulba/pipelines.py
> +        self.buffer_adds_count[actor_id] += 1
Yep, just an artifact. Was used to track when we should call `self.rate_limiter.insert()` instead we insert fractions now `self.rate_limiter.insert(1 / self.num_buffers)`

2025-02-10 13:26 UTC, Louay-Ben-nessir commented on mava/configs/system/q_learning/rec_iql.yaml
> +error_tolerance:  ~ # Tolerance for how much the learner/actor can sample/insert before being blocked. Must be greater than 2 to avoid deadlocks.
I think 4 is reasonable, Most of the top SMAC runs had 2 but some had 16

2025-02-10 18:03 UTC, Louay-Ben-nessir commented on mava/systems/q_learning/sebulba/rec_iql.py
> +    print(f"{Fore.RED}{Style.BRIGHT}All threads stopped...{Style.RESET_ALL}")
definitely, I've been meaning to also move this to before the  `absolute_metric` to avoid having the actor running in the background

2025-02-13 07:39 UTC, sash-a submitted a review, later dismissed
:fire:

2025-02-13 07:40 UTC, sash-a commented on mava/systems/q_learning/sebulba/rec_iql.py
> +            config.system.eps_min, 1 - (t / config.system.eps_decay) * (1 - config.system.eps_min)
I think rather leave it for now, no need to make this more complex

2025-02-27 13:37 UTC, SimonDuToit requested changes
Looks good! Just one request and one question.

2025-02-27 13:37 UTC, SimonDuToit commented on mava/utils/sebulba/pipelines.py
> +        while not self._should_stop:
Please update the (online) pipeline with the changes recently merged into dev, which adds support for hstates.

2025-02-27 13:39 UTC, SimonDuToit commented on mava/wrappers/gym.py
> +        )  # (B,) --> (B, N)
Also: if terminated is repeated for num_agents in the wrapper, should we still be repeating dones for num_agents in the systems? Because I see you didn't remove this from sebulba PPO. Or does this not actually effect the dones?

2025-03-10 13:40 UTC, Louay-Ben-nessir commented on mava/wrappers/gym.py
> +        )  # (B,) --> (B, N)
Yes, this doesn't affect the dones, it's only used for discount calculations. The step_type is still of shape (num_envs,)
I double checked and the TS chapes are the same in Anakin and Sebulba

2025-03-11 13:47 UTC, SimonDuToit approved these changes
LGTM

2025-03-11 14:54 UTC, sash-a approved these changes
:fire: :fire:

2025-03-11 14:55 UTC, merged