feature: add optional observation network to ppo default networks
instadeepai/Mava pull request #502
Opened 2022-05-06 13:42 UTC by sash-a

## What?
PPO default networks now takes an optional observation argument
## Why?
To allow for observation networks in cases where it would be beneficial (such as 2D observations)
## How?
The `observation_network` argument was added to the three network creation methods in `networks.py`. It defaults to a `batch_concat` so that the observations are 1D and the current behavior is preserved by default. However, the user can specify a custom network for this, an example can be seen in `run_mappo_obs_net.py`

2022-05-06 13:44 UTC, sash-a commented on examples/jax/debugging/simple_spread/feedforward/decentralised/run_mappo_obs_net.py
> +    )
Currently there is no env in mava that produces 2D observations (that I could find). So this example does fail, as the network is an Atari net which has convs and thus expects a 2D input.

2022-05-27 13:54 UTC, KaleabTessera commented
Hi @sash-a , thanks for this! 

Please use pong or co-op pong in the example (https://github.com/instadeepai/Mava/blob/develop/examples/tf/petting_zoo/atari/pong/recurrent/decentralised/run_madqn.py or https://github.com/instadeepai/Mava/blob/develop/examples/tf/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_mappo.py) . These envs have pixel obs.

2022-06-09 14:03 UTC, mmorris44 reviewed
~~I'm having trouble actually running this (in docker). We can only build one target at a time, so I can't build `jax-core` and `pz` at the same time to be able to run this code.~~ -> use target `pz-jax`. My bad

2022-06-09 14:15 UTC, mmorris44 requested changes
Requested changes due to one line I'm confused by. Otherwise looks good!

2022-06-09 14:50 UTC, mmorris44 submitted a review, later dismissed
Approval pending confirmation that example runs fine in docker

2022-06-09 15:17 UTC, mmorris44 approved these changes
Approved! Thanks @sash-a :)

2022-06-09 15:18 UTC, merged