tests: data server component unit tests
instadeepai/Mava pull request #622
Opened 2022-07-07 16:39 UTC by RuanJohn

## What?
Unit tests for `DataServer` components.
## Why?
Part of expanding test code coverage for callback redesign Jax-based Mava.  
## Extra
Existing dataserver tests were moved to `tests/jax/integration` since they depended on multiple components. We will utilize there tests as part of the integration tests. 
closes #521

2022-07-14 07:12 UTC, OmaymaMahjoub requested changes
I had a look at the unit test and it is good just two missing things to verify also the integration can't be in another branch? or at least we need to change the PR name because this PR is for a unit test from what I think?

2022-07-14 07:12 UTC, OmaymaMahjoub commented on tests/jax/components/building/data_server_test.py
> +    assert table.info.max_size == 1000
I think we need to verify the name and signature here of the table

2022-07-14 07:12 UTC, OmaymaMahjoub commented on tests/jax/components/building/data_server_test.py
> +    assert table.info.max_size == 1000
same here

2022-07-14 08:50 UTC, RuanJohn commented on tests/jax/components/building/data_server_test.py
> +    assert table.info.max_size == 1000
Sorted.

2022-07-14 09:11 UTC, OmaymaMahjoub approved these changes
Looks good! Thanks @RuanJohn

2022-07-18 09:06 UTC, AsadJeewa approved these changes
Thanks @RuanJohn! Clean code and you covered all the different params/ configs

2022-07-18 14:31 UTC, merged