feature (idqn): quantile regression dqn
instadeepai/Mava pull request #897
Opened 2023-02-22 12:28 UTC by sash-a

## What?
Quantile Regression IDQN
## Why?
An improvement to IDQN

2023-02-22 16:39 UTC, siddarthsingh1 requested changes
Thanks @sash-a, looks good to me. There's just a few naming changes that might be worth looking at.

2023-02-22 16:39 UTC, siddarthsingh1 commented on mava/systems/idqn/components/training/qr_loss.py
> +            """Surrogate loss using clipped probability ratios.
Needs to be changed to the QR-DQN explanation.

2023-02-22 16:39 UTC, siddarthsingh1 commented on mava/systems/idqn/quantile_network.py
> +        """A container for IDQN networks.
Needs to be changed to QR-DQN description.

2023-02-22 16:39 UTC, siddarthsingh1 commented on mava/systems/idqn/quantile_network.py
> +        weighted_gready_probs = (1 - epsilon) * greedy_actions_probs
It should be `weighted_greedy_probs` instead of `weighted_gready_probs`.

2023-02-22 16:39 UTC, siddarthsingh1 commented on mava/systems/idqn/quantile_network.py
> +        # q_dist = model(inputs).reshape(-1, num_actions, num_atoms)
Do we need this commented out line?

2023-02-22 16:39 UTC, siddarthsingh1 commented on mava/systems/idqn/quantile_network.py
> +        networks: IDQN networks created to given spec
Maybe we should specify IQR-DQN here?

2023-07-11 07:28 UTC, DriesSmit commented
Closing this PR now. We are shifting focus towards an anakin style JAX multi-agent repo.

2023-07-11 07:28 UTC, closed without merging