chore: release ci cleanup
instadeepai/Mava pull request #910
Opened 2023-08-10 13:43 UTC by sash-a

Reconfigured the workflow, requirements, tests and the like. Mostly copying jumanji were appropriate

2023-08-10 13:44 UTC, sash-a commented
Probably going to need merge this in after all the old mava stuff has been deleted, otherwise it won't pass the checks

2023-08-11 08:19 UTC, RuanJohn requested changes
Thanks @sash-a! What a mammoth job! This looks super clean!
Just a few minor requests from my side.

2023-08-11 08:19 UTC, RuanJohn commented on .gitignore
>  3rdparty
Since we won't be supporting smac we can remove this for now.

2023-08-11 08:19 UTC, RuanJohn commented on setup.py
> +        "Development Status :: 4 - Beta",
No exactly sure about this? Aren't we in alpha at the moment?

2023-08-11 10:06 UTC, RuanJohn approved these changes
Looks good to me! Thanks @sash-a :fire:

2023-08-11 10:26 UTC, RuanJohn commented
> 

Very good points, just some comments on them: 
* The troubleshooting will get removed in the readme PR. 
* For now, let's hold off on doing this and have one PR once all the systems are in where we move things around. 
* Very good catch. Can we please bring the Mava logo back @sash-a? My suggestion is that we keep it in the docs folder in `docs/images/`.

2023-08-11 11:23 UTC, RuanJohn approved these changes
Thanks @sash-a :raised_hands:

2023-08-11 11:24 UTC, merged