Docs/refactor
instadeepai/Mava pull request #937
Opened 2023-09-13 13:36 UTC by arnupretorius

## What?
Small PR to clean up the landing page. Move some of the markdowns to the docs folder and the notebook to an examples folder.

## Why?
Simpler and easier to read.

2023-09-15 07:01 UTC, RuanJohn requested changes
Thank you @arnupretorius :raised_hands: 
One minor detail, can you also please fix the link in the starter notebook itself for launching on Colab.

2023-09-15 14:48 UTC, RuanJohn submitted a review, later dismissed
Thanks @arnupretorius :raised_hands:

2023-09-18 08:09 UTC, OmaymaMahjoub submitted a review, later dismissed
Looks good! Just minor change that we can skip if we think it is unnecessary :)

2023-09-18 08:09 UTC, OmaymaMahjoub commented on README.md
> +[quickstart]: https://github.com/instadeepai/Mava/blob/develop//examples/Quickstart.ipynb
Minor improvement (although it works without changing it):  `develop//examples/` -> `develop/examples/`

2023-09-18 11:01 UTC, OmaymaMahjoub approved these changes

2023-09-18 13:40 UTC, RuanJohn approved these changes

2023-09-18 13:58 UTC, merged