Feat/make file utils
instadeepai/Mava pull request #958
Opened 2023-12-06 13:55 UTC by WiemKhlifi

## What?
Add new functions to create environments using the `create_envs_utils` file in ` mava.utils`.
## Why?
Instead of creating different file systems for each environment, we use a single file system and remove the common lines that create the environments. 
## How?
* Added a `create_envs_utils` file in ` mava.utils`: Create environments from config files. 
* Remove the common lines from systems files and use the `create_environment ` function.
* Edit configs to differentiate between the **ippo** and **mappo** systems
## Note: 
File names will be changed later, so as not to consider that a new file has been created and the old one deleted.

2023-12-06 14:19 UTC, sash-a requested changes
Very nice, just minor things like `make...` instead of `create...` to stay consistent with gym, but this PR is almost ready to go :fire:

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +    if config["system"]["system_name"] in ["ff_mappo", "rec_mappo"]:
I think system name isn't the way to do this, rather `add_global_state` so we don't have to check each system and then its also consistent with `add_agent_id`

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +def create_jumanji_env(env_name: str, config: Dict) -> Tuple[Environment, Environment]:
```suggestion
def make_jumanji_env(env_name: str, config: Dict) -> Tuple[Environment, Environment]:
```

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
rename to `make_env.py`

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +    """
nit:
```suggestion
    """
    Create a Jumanji environments for training and evaluation.
    
    Args:
        env_name (str): The name of the environment to create.
        config (Dict): The configuration of the environment.

    Returns:
        A tuple of the environments.
    """
```

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +        raise ValueError(f"{env_name} is not a supported environment.")
Very nice :fire:

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +}
Also very nice :fire:

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +def create_jaxmarl_env(config: Dict) -> Environment:
```suggestion
def make_jaxmarl_env(config: Dict) -> Environment:
```

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +        A JAXMARL environment.
```suggestion
    Create a JAXMARL environment.
    
    Args:
        config (Dict): The configuration of the environment.
        
    Returns:
        A JAXMARL environment.
```

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +def create_environment(config: Dict) -> Tuple[Environment, Environment]:
```suggestion
def make(config: Dict) -> Tuple[Environment, Environment]:
```

2023-12-06 14:19 UTC, sash-a commented on mava/utils/create_envs_utils.py
> +JumanjiRegistry = {
```suggestion
_jumanji_registry = {
```

2023-12-06 14:32 UTC, RuanJohn reviewed
Very very nice @WiemKhlifi :fire: 
I agree with Sasha's suggestion. Also, feel free to change the file names.

2023-12-06 15:26 UTC, WiemKhlifi commented
> Very nice, just minor things like `make...` instead of `create...` to stay consistent with gym, but this PR is almost ready to go 🔥

All the changes have been made 🙌 . I think this report is now ready or not yet?

2023-12-07 08:18 UTC, sash-a approved these changes
Looks great, glad we have a really nice way of switching between envs now :fire:

2023-12-07 12:49 UTC, RuanJohn approved these changes
Very nice! Thank you @WiemKhlifi :fire:

2023-12-07 13:37 UTC, RuanJohn approved these changes

2023-12-07 13:41 UTC, merged