feat: Vault PoC
instadeepai/Mava pull request #964
Opened 2023-12-11 14:01 UTC by callumtilbury

## What?
Proof of concept for using Vault in a Mava system.

## Why?
Allows us to store data to be used in, e.g., OG-MARL.

## How?
Vault functionality from flashbax—currently sitting on a [branch](https://github.com/instadeepai/flashbax/tree/feat/vault).

## Extra
n/a

2023-12-12 08:57 UTC, OmaymaMahjoub requested changes
LGTM! Just minor request to develop the intro of the readme by explaining more the motivation behind recording with mava ppo to og-marl :pray:

2023-12-12 13:14 UTC, RuanJohn approved these changes
Super nice @callumtilbury :fire: :alien:

2023-12-13 05:58 UTC, callumtilbury commented
Thanks @OmaymaMahjoub! Tried to add some more info to the READMEs. Let me know if anything else should be added 🙏🏻

2023-12-13 07:01 UTC, RuanJohn approved these changes
LGTM :fire:

2023-12-13 10:04 UTC, OmaymaMahjoub approved these changes
Thanks @callumtilbury :alien:

2023-12-13 10:05 UTC, merged