feat: stop accessing LogEnvState variables directly
instadeepai/Mava pull request #994
Opened 2024-01-18 15:49 UTC by sash-a

## What?
Stop accessing `LogEnvState` variables directly as this forces us to always make the `LogEnvWrapper` the outermost wrapper - so we can access it's variables through `state.episode_return` instead of `state.env_state.episode_return` and if we have an unknown number of wrappers we can't know how deep in the `env_state` chain we have to go. So instead pass the variables we care about through `timestep.extras`.

Also changed some file names to make stuff more clear :smile: 
Also renamed the `LogEnvState` to bring it more inline with the gym wrapper that does similar things.

## Why?
Allows for vault wrapper to also not be the outermost wrapper if we start passing the state info through `timestep.extras`

2024-01-19 10:14 UTC, callumtilbury approved these changes
Great stuff! Thanks @sash-a

2024-01-19 10:14 UTC, callumtilbury approved these changes
Great stuff! Thanks @sash-a! 🚀

2024-01-19 13:58 UTC, callumtilbury requested changes

2024-01-19 13:58 UTC, callumtilbury commented on mava/wrappers/episode_metrics.py
> +        timestep.extras["episode_metrics"] = {"episode_return": 0.0, "episode_length": 0}
Sorry, I missed this first time around! I'm hitting an error:
```
Traceback (most recent call last):
  File "/Users/callum/Mava/mava/systems/ff_ippo.py", line 584, in hydra_entry_point
    run_experiment(cfg)
  File "/Users/callum/Mava/mava/systems/ff_ippo.py", line 457, in run_experiment
    learn, actor_network, learner_state = learner_setup(
  File "/Users/callum/Mava/mava/systems/ff_ippo.py", line 404, in learner_setup
    env_states, timesteps = jax.vmap(env.reset, in_axes=(0))(
  File "/Users/callum/Mava/mava/wrappers/episode_metrics.py", line 50, in reset
    timestep.extras["episode_metrics"] = {"episode_return": 0.0, "episode_length": 0}
TypeError: 'NoneType' object does not support item assignment
```

And I think we ought to write:
```suggestion
        if timestep.extras is None:
            timestep.extras = {}
        timestep.extras["episode_metrics"] = {"episode_return": 0.0, "episode_length": 0}
```

2024-01-19 14:02 UTC, callumtilbury commented on mava/wrappers/episode_metrics.py
> +        timestep.extras["episode_metrics"] = {"episode_return": 0.0, "episode_length": 0}
Solved by bumping Jumanji version :)

2024-01-22 07:50 UTC, callumtilbury approved these changes, later dismissed

2024-01-22 08:12 UTC, OmaymaMahjoub requested changes
Thanks @sash-a! Happy to approve the PR once the comments are addressed!

2024-01-22 08:12 UTC, OmaymaMahjoub commented on mava/wrappers/marl.py
Maybe `observation_wrappers.py` is better as a name for this file

2024-01-22 08:12 UTC, OmaymaMahjoub commented on mava/wrappers/episode_metrics.py
If you can check the possibility of using this during evaluation, it will make evaluation much easier to read and maybe having same type of output as the trainer :thinking:

2024-01-24 09:19 UTC, sash-a commented on mava/wrappers/episode_metrics.py
Yes, so I did look into this, wanted to use the `TrainState` also. Only issue is that the evaluator currently takes in `EvalState`, `params` and an `apply_fn` which I think makes it very nice and general. If we use `TrainState` then we'd use the params in the train state and so it would be a bit less general, but it is something worth looking into. Maybe I can make an issue for this as it's quite a big change?

2024-01-24 09:20 UTC, sash-a commented on mava/wrappers/marl.py
Nice, much better name :smile:

2024-01-24 09:22 UTC, sash-a commented on mava/wrappers/marl.py
Called it `observation.py` as we're already in the `wrappers` folder and the rest of the files don't have the _wrapper part, hope that's ok :smile:

2024-01-24 11:02 UTC, OmaymaMahjoub commented on mava/wrappers/episode_metrics.py
yeah if you can make an issue related to that as I am currently not satisfied with our evaluator code, it must be there another better way to handle things within it :sweat_smile:

2024-01-24 11:04 UTC, OmaymaMahjoub submitted a review, later dismissed
Thanks @sash-a :fire:

2024-01-29 13:02 UTC, RuanJohn submitted a review, later dismissed
LGTM :ship:

2024-01-29 15:12 UTC, OmaymaMahjoub requested changes
If you can double check the quickstart notebook working properly else happy to approve :raised_hands:

2024-01-29 15:35 UTC, OmaymaMahjoub commented
> If you can double check the quickstart notebook working properly else happy to approve 🙌

I tested the notebook and it raises some errors, the main changes should be fixing the imports, getting the episode return from timesteps.extras, and using `RecordEpisodeMetricsState` instead of `LogWrapper`

2024-02-02 15:36 UTC, RuanJohn submitted a review, later dismissed
:spider:

2024-02-05 09:26 UTC, OmaymaMahjoub approved these changes
I fixed the quickstart notebook :sweat_smile:, thanks @sash-a for this PR :fire:

2024-02-05 10:18 UTC, RuanJohn approved these changes
Thank you @sash-a :raised_hands:

2024-02-05 10:19 UTC, merged