fix: bug fixes + add missing kwargs
instadeepai/Mava pull request #995
Opened 2024-01-24 09:12 UTC by WiemKhlifi

## What?
Set the appropriate type for `episode_return` in the `Checkpointer` class, fix the `ExperimentOutput` type in the quickstart notebook, and add missing kwargs in the `jumanji_make_env` function.
## Why?
The changes made have resolved the bugs identified.

2024-01-26 12:11 UTC, OmaymaMahjoub commented on examples/Quickstart.ipynb
@WiemKhlifi  double check the rware version that you are using, as I can see from the rendering and results that you are using the old version of rware before the fix that was made in jumanji.

2024-01-26 12:17 UTC, OmaymaMahjoub requested changes
Thanks @WiemKhlifi, if you can rerun the notebook with the correct rware version and from there happy to approve the PR

2024-01-26 12:17 UTC, OmaymaMahjoub commented on mava/utils/make_env.py
> +    env = jumanji.make(env_name, generator=generator, **config.env.kwargs)
Nice catch!

2024-01-29 10:29 UTC, WiemKhlifi commented
All checks are done 🙌

2024-01-29 12:47 UTC, sash-a reviewed
Nice, I like this just need to wait for #994 I think

2024-01-29 12:47 UTC, sash-a commented on mava/utils/logger.py
> +            } | metrics
I definitely change this in #994. Can we get that in first? And then make the change on top of that?

2024-01-29 13:07 UTC, sash-a commented on mava/utils/logger.py
> +            } | metrics
Scratch that I was thinking of the other logging PR, so never mind this. Will approve :smile:

2024-01-29 13:07 UTC, sash-a approved these changes
:fire_engine: :fire:

2024-01-29 15:03 UTC, OmaymaMahjoub approved these changes
Thanks @WiemKhlifi  LGTM!

2024-01-29 15:06 UTC, merged